import type { Metadata } from 'next'
import Link from 'next/link'
import '../../public/css/style.css'
import Image from "next/image"
import Logo from '../../public/images/logo.png'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header>
          <Link href={`/listes`}>Listes</Link>
          <Link href={`/panoplie`}>Stuffs</Link>
          <Link href={`/`}><Image src={Logo} alt="" /></Link>
          <Link href={`/login`}>connexion</Link>
          <Link href={`/register`}>nous rejoindre</Link>
      </header>
      {children}
      </body>
    </html>
  )
}
